services:
  db-dev:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
  redis-dev:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker-data/redis:/data
