name: youtubemate-test-watch

services:
  db-test:
    extends:
      file: docker-compose.yml
      service: db
  redis-test:
    extends:
      file: docker-compose.yml
      service: redis
  app-test:
    extends:
      file: docker-compose.test.yml
      service: app-test
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4173:4173
    environment:
      - PWTEST_WATCH=1
    command: >
      sh -c "dotenv -e .env.test -- npm run migrate:init && \
        dotenv -e .env.test -- npx prisma db seed && \
        dotenv -e .env.test -- npx prisma generate && \
        dotenv -e .env.test -- npm run build && \
        dotenv -e .env.test -- npx playwright test"
