services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.yml
      service: redis
    volumes:
      - ./docker-data/redis:/data
